### ISSUE TITLE
Support for Intan 1024ch recording controllers?

### ISSUE THREAD

**Issue by kimqi** [open-ephys-plugins/rhythm-plugins#8]
Hello!
Are there any plans to add support for Intan 1024ch recording controllers on OE0.6.6? We're still stuck using 0.5.5 and are having difficulty using newer plugins and am wanting to upgrade

Thanks!
Brian

**Comment by anjaldoshi** [comment]
Hi Brian,

We already added support for Intan 512 and 1024 Recording Controllers to Open Ephys GUI v0.6.x a while ago via the RHD Recording Controller plugin. You'll need to install the plugin via Plugin Installer. Although, it doesn't support the newer XEM7310 boards (Issue #7 ), if your controller is working with GUI v0.5.5, it should work with GUI v0.6.6.

**Comment by kimqi** [comment]
Hi,
Thanks for the response. However, I can detect a signal if I connect a 32ch headstage to my intan controller on 0.5.5 but not 0.6.6 with everything else being identical setup-wise. Do you recommend any troubleshooting steps?

**Comment by anjaldoshi** [comment]
Can you copy the console output of v0.6.6 and send it to support@open-ephys.org? Someone from the team who has access to similar hardware will try to help you troubleshoot this.

**Comment by jsiegle** [comment]
Using the **RHD Recording Controller** plugin instead of the **Intan RHD USB** plugin fixed the issue.
